stdlib.code containing bool.to_string implementation

diff --git a/lint b/lint
--- a/lint
+++ b/lint
@@ -1,4 +1,8 @@
 #!/bin/sh
+if ! which black isort mypy pyflakes >/dev/null; then
+    echo "can't find stuff, is venv active?"
+    exit 1
+fi
 black compiler
 isort compiler
 mypy compiler
